"""Initial migration

Revision ID: 8f617b4b5aed
Revises: 
Create Date: 2025-12-17 18:36:46.298128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f617b4b5aed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otps_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_otps_expires_at'), ['expires_at'], unique=False)

    op.create_table('sports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sports_code'), ['code'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)

    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leagues_sport_id'), ['sport_id'], unique=False)

    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_code', sa.String(length=50), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participants_short_code'), ['short_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_participants_sport_id'), ['sport_id'], unique=False)

    op.create_table('scoring_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('max_score', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('alpha', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('beta', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('formula_type', sa.Enum('LINEAR_NORMALIZED', 'SIGMOID', 'PIECEWISE', name='formulatype'), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scoring_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scoring_rules_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_scoring_rules_sport_id'), ['sport_id'], unique=False)

    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_code', sa.String(length=50), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_short_code'), ['short_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_sport_id'), ['sport_id'], unique=False)

    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('locked_balance', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallets_user_id'), ['user_id'], unique=True)

    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('PARTICIPANT', 'TEAM', 'PROP', name='assettype'), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_participant_id'), ['participant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_symbol'), ['symbol'], unique=True)
        batch_op.create_index(batch_op.f('ix_assets_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_type'), ['type'], unique=False)

    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('transaction_type', sa.Enum('DEPOSIT', 'WITHDRAWAL', 'BUY', 'SELL', 'SETTLEMENT', 'FEE', name='transactiontype'), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_entries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_reference_id'), ['reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_transaction_type'), ['transaction_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_wallet_id'), ['wallet_id'], unique=False)

    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('UPCOMING', 'ACTIVE', 'FINISHED', name='seasonstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seasons_league_id'), ['league_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seasons_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_seasons_year'), ['year'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('venue', sa.String(length=200), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('UPCOMING', 'LIVE', 'FINISHED', name='eventstatus'), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_season_id'), ['season_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_start_at'), ['start_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_status'), ['status'], unique=False)

    op.create_table('participant_team_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('participant_team_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participant_team_memberships_participant_id'), ['participant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_participant_team_memberships_season_id'), ['season_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_participant_team_memberships_team_id'), ['team_id'], unique=False)

    op.create_table('event_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('primary_score', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('FINISHED', 'DNF', 'DISQUALIFIED', name='resultstatus'), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'participant_id', name='uq_event_participant')
    )
    with op.batch_alter_table('event_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_results_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_results_participant_id'), ['participant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_results_rank'), ['rank'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_results_status'), ['status'], unique=False)

    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('scoring_rule_id', sa.Integer(), nullable=False),
    sa.Column('market_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'SETTLED', name='marketstatus'), nullable=False),
    sa.Column('a', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('b', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['scoring_rule_id'], ['scoring_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_markets_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_markets_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_markets_scoring_rule_id'), ['scoring_rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_markets_status'), ['status'], unique=False)

    op.create_table('market_settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('settled_at', sa.DateTime(), nullable=False),
    sa.Column('settlement_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('payout_per_share', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_settlements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_settlements_market_id'), ['market_id'], unique=True)

    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('avg_entry_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('last_marked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'market_id', name='uq_user_market')
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_positions_market_id'), ['market_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_user_id'), ['user_id'], unique=False)

    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_history_market_id'), ['market_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_history_timestamp'), ['timestamp'], unique=False)

    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('buyer_user_id', sa.Integer(), nullable=False),
    sa.Column('seller_user_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['seller_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trades_buyer_user_id'), ['buyer_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_executed_at'), ['executed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_market_id'), ['market_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_seller_user_id'), ['seller_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trades_seller_user_id'))
        batch_op.drop_index(batch_op.f('ix_trades_market_id'))
        batch_op.drop_index(batch_op.f('ix_trades_executed_at'))
        batch_op.drop_index(batch_op.f('ix_trades_buyer_user_id'))

    op.drop_table('trades')
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_history_timestamp'))
        batch_op.drop_index(batch_op.f('ix_price_history_market_id'))

    op.drop_table('price_history')
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_positions_user_id'))
        batch_op.drop_index(batch_op.f('ix_positions_market_id'))

    op.drop_table('positions')
    with op.batch_alter_table('market_settlements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_settlements_market_id'))

    op.drop_table('market_settlements')
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_markets_status'))
        batch_op.drop_index(batch_op.f('ix_markets_scoring_rule_id'))
        batch_op.drop_index(batch_op.f('ix_markets_event_id'))
        batch_op.drop_index(batch_op.f('ix_markets_asset_id'))

    op.drop_table('markets')
    with op.batch_alter_table('event_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_results_status'))
        batch_op.drop_index(batch_op.f('ix_event_results_rank'))
        batch_op.drop_index(batch_op.f('ix_event_results_participant_id'))
        batch_op.drop_index(batch_op.f('ix_event_results_event_id'))

    op.drop_table('event_results')
    with op.batch_alter_table('participant_team_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participant_team_memberships_team_id'))
        batch_op.drop_index(batch_op.f('ix_participant_team_memberships_season_id'))
        batch_op.drop_index(batch_op.f('ix_participant_team_memberships_participant_id'))

    op.drop_table('participant_team_memberships')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_status'))
        batch_op.drop_index(batch_op.f('ix_events_start_at'))
        batch_op.drop_index(batch_op.f('ix_events_season_id'))

    op.drop_table('events')
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seasons_year'))
        batch_op.drop_index(batch_op.f('ix_seasons_status'))
        batch_op.drop_index(batch_op.f('ix_seasons_league_id'))

    op.drop_table('seasons')
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_entries_wallet_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_transaction_type'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_reference_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_created_at'))

    op.drop_table('ledger_entries')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_type'))
        batch_op.drop_index(batch_op.f('ix_assets_team_id'))
        batch_op.drop_index(batch_op.f('ix_assets_symbol'))
        batch_op.drop_index(batch_op.f('ix_assets_participant_id'))

    op.drop_table('assets')
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallets_user_id'))

    op.drop_table('wallets')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_sport_id'))
        batch_op.drop_index(batch_op.f('ix_teams_short_code'))

    op.drop_table('teams')
    with op.batch_alter_table('scoring_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scoring_rules_sport_id'))
        batch_op.drop_index(batch_op.f('ix_scoring_rules_code'))

    op.drop_table('scoring_rules')
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participants_sport_id'))
        batch_op.drop_index(batch_op.f('ix_participants_short_code'))

    op.drop_table('participants')
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leagues_sport_id'))

    op.drop_table('leagues')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('sports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sports_code'))

    op.drop_table('sports')
    with op.batch_alter_table('otps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otps_expires_at'))
        batch_op.drop_index(batch_op.f('ix_otps_email'))

    op.drop_table('otps')
    # ### end Alembic commands ###
